disabled_rules:
  - type_name
  - line_length
  - identifier_name
  - trailing_whitespace
  - unused_closure_parameter

excluded:
  - Pods
  - iMast/*/*/R.generated.swift
  - vendor

force_cast: warning
force_try: warning

trailing_comma:
  mandatory_comma: true
