language: objective-c
osx_image: xcode9.3
before_install:
  - gem install xcpretty
install:
  - travis_wait pod install --repo-update
script:
  - xcodebuild -workspace iMast.xcworkspace -list
  - set -o pipefail && xcodebuild clean build -sdk iphonesimulator -workspace iMast.xcworkspace -scheme iMast CODE_SIGNING_REQUIRED=NO | xcpretty -c
cache:
  edge: true
  directories:
    - Pods
