name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode:
          - 12_beta
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    - name: bundle install
      run: bundle update --bundler && bundle install
    - name: Install CocoaPods dependencies
      run: bundle exec pod install
    - name: Build
      run: set -o pipefail && xcodebuild clean build -sdk iphonesimulator -workspace iMast.xcworkspace -scheme iMast CODE_SIGNING_REQUIRED=NO | xcpretty -c
