name: CI

on: [push]

jobs:
  build:
    # for contributors or forked version developers: macOS-11 image is currently private beta,
    # so if you want to use macOS-11 outside of cinderella-project org, you should submit to private beta.
    # more information: https://github.com/actions/virtual-environments/blob/main/docs/macos-11-onboarding.md
    runs-on: macOS-11
    strategy:
      matrix:
        xcode:
          - "12.5"
          - "13.0"
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    - name: bundle install
      run: bundle update --bundler && bundle install
    - name: Install CocoaPods dependencies
      run: bundle exec pod install
    - name: Build
      run: set -o pipefail && xcodebuild clean build -sdk iphonesimulator -workspace iMast.xcworkspace -scheme "iMast iOS" CODE_SIGNING_REQUIRED=NO | xcpretty -c
